{"uuid":"39e5c555-a7a1-44cc-b90f-040b9d0db3c5","historyId":"92604d761ce3478790fd8a015b9a7230","fullName":"cn.zxs.mybatis.dao.impl.UserDaoImplTest.testQueryUserAll","labels":[{"name":"package","value":"cn.zxs.mybatis.dao.impl.UserDaoImplTest"},{"name":"testClass","value":"cn.zxs.mybatis.dao.impl.UserDaoImplTest"},{"name":"testMethod","value":"testQueryUserAll"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Automated_UI"},{"name":"subSuite","value":"cn.zxs.mybatis.dao.impl.UserDaoImplTest"},{"name":"host","value":"DESKTOP-C8CNVHF"},{"name":"thread","value":"6480@DESKTOP-C8CNVHF.main(1)"}],"links":[],"name":"testQueryUserAll","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\r\n### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n### The error may exist in mappers/UserDaoMapper.xml\r\n### The error may involve UserDao.queryUserAll\r\n### The error occurred while executing a query\r\n### Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.","trace":"org.apache.ibatis.exceptions.PersistenceException: \r\n### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n### The error may exist in mappers/UserDaoMapper.xml\r\n### The error may involve UserDao.queryUserAll\r\n### The error occurred while executing a query\r\n### Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98)\r\n\tat cn.zxs.mybatis.dao.impl.UserDaoImpl.queryUserAll(UserDaoImpl.java:22)\r\n\tat cn.zxs.mybatis.dao.impl.UserDaoImplTest.testQueryUserAll(UserDaoImplTest.java:37)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:645)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:756)\r\n\tat org.testng.TestRunner.run(TestRunner.java:610)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:289)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1133)\r\n\tat org.testng.TestNG.run(TestNG.java:1104)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)\r\nCaused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)\r\n\tat com.mysql.jdbc.Util.handleNewInstance(Util.java:408)\r\n\tat com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1137)\r\n\tat com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:355)\r\n\tat com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2490)\r\n\tat com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2527)\r\n\tat com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2309)\r\n\tat com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)\r\n\tat com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)\r\n\tat com.mysql.jdbc.Util.handleNewInstance(Util.java:408)\r\n\tat com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:419)\r\n\tat com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)\r\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)\r\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)\r\n\tat org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:195)\r\n\tat org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:190)\r\n\tat org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:92)\r\n\tat org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:375)\r\n\tat org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:84)\r\n\tat org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:134)\r\n\tat org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:61)\r\n\tat org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:279)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:72)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:59)\r\n\tat org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)\r\n\tat org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)\r\n\tat org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)\r\n\tat org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)\r\n\t... 28 more\r\nCaused by: java.net.ConnectException: Connection refused: connect\r\n\tat java.base/sun.nio.ch.Net.connect0(Native Method)\r\n\tat java.base/sun.nio.ch.Net.connect(Net.java:503)\r\n\tat java.base/sun.nio.ch.Net.connect(Net.java:492)\r\n\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)\r\n\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)\r\n\tat java.base/java.net.Socket.connect(Socket.java:648)\r\n\tat java.base/java.net.Socket.connect(Socket.java:597)\r\n\tat java.base/java.net.Socket.<init>(Socket.java:520)\r\n\tat java.base/java.net.Socket.<init>(Socket.java:328)\r\n\tat com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:258)\r\n\tat com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:305)\r\n\t... 58 more\r\n"},"stage":"finished","start":1594649664354,"stop":1594649666580,"parameters":[]}